spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 'QpLpYnh619!'
    url: jdbc:mysql://172.16.10.187:3306/manager-demo?serverTimezone=GMT%2b8&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf8&useUnicode=true&&allowMultiQueries=true

server:
  port: 8999
